---
- name: set wifi-devices
  include: set_wifi_device.yml
  vars:
    name: "{{item.name}}"
    enabled: "{{item.enabled}}"
    channel: "{{item.channel | default({})}}"
    txpower: "{{item.txpower | default({})}}"
    country: "{{item.country | default({})}}"
  with_items: "{{wifi_devices}}"
  notify:
    - uci commit wireless
    - reload network

- name: set wifi-ifaces
  include: set_wifi_iface.yml
  vars:
    index: "{{item.0}}"
    device: "{{item.1.device | default({})}}"
    network: "{{item.1.network | default({})}}"
    mode: "{{item.1.mode | default({})}}"
    ssid: "{{item.1.ssid | default({})}}"
    encryption: "{{item.1.encryption | default({})}}"
    key: "{{item.1.key | default({})}}"
    macfilter: "{{item.1.macfilter | default({})}}"
    maclist: "{{item.1.maclist | default({})}}"
  with_indexed_items: "{{wifi_ifaces}}"
  notify:
    - uci commit wireless
    - reload network
