---
- name: set wifi-devices
  uci: command=set config="wireless" section="{{item.name}}" option="disabled" value="{{ (not item.enabled) | int }}"
  with_items: "{{wifi_devices}}"
  notify:
    - uci commit wireless
    - reload network
