---
- name: set wifi-devices
  uci: command=set config="wireless" section="{{item.name}}" option="disabled" value="{{ (not item.enabled) | int }}"
  with_items: "{{wifi_devices}}"
  notify:
    - uci commit wireless
    - reload network

- name: set wifi-ifaces
  include: set_wifi_iface.yml index={{item.0}} device="{{item.1.device | default({})}}" network="{{item.1.network | default({})}}" mode="{{item.1.mode | default({})}}" ssid="{{item.1.ssid | default({})}}" encryption="{{item.1.encryption | default({})}}" key="{{item.1.key | default({})}}"
  with_indexed_items: "{{wifi_ifaces}}"
  notify:
    - uci commit wireless
    - reload network
