---
- name: set wifi-devices
  uci:
    command: set_object
    config: wireless
    type: "wifi-device"
    section: "{{ item.name }}"
    values:
      disabled: "{{ (not item.enabled) | int }}"
      channel: "{{ item.channel | default(None) }}"
      txpower: "{{ item.txpower | default(None) }}"
      htmode: "{{ item.htmode | default(None) }}"
  with_items: "{{ wifi_devices }}"
  notify:
    - uci commit wireless
    - reload network

- name: set wifi-interfaces
  uci:
    command: set_object
    config: wireless
    type: "wifi-iface"
    index: "{{ item.1.index | default(item.0) }}"
    values:
      device: "{{ item.1.device | default(None) }}"
      network: "{{ item.1.network | default(None) }}"
      mode: "{{ item.1.mode | default(None) }}"
      ssid: "{{ item.1.ssid | default(None) }}"
      encryption: "{{ item.1.encryption | default('none') }}"
      key: "{{ item.1.key | default(None) }}"
      macfilter: "{{ item.1.macfilter | default(None) }}"
      maclist: "{{ item.1.maclist | default([]) }}"
      isolate: "{{ item.1.isolate | default(None) | int(None) }}"
  with_indexed_items: "{{ wifi_ifaces }}"
  notify:
    - uci commit wireless
    - reload network
