---
- name: set wifi-device disabled
  uci:
    command: set
    config: "wireless"
    section: "{{name}}"
    option: "disabled"
    value: "{{ (not enabled) | int }}"
  notify:
    - uci commit wireless
    - reload network for openwrt-wireless

- name: set wifi-device channel
  uci:
    command: set
    config: "wireless"
    section: "{{name}}"
    option: "channel"
    value: "{{channel}}"
  when: channel != {}
  notify:
    - uci commit wireless
    - reload network for openwrt-wireless

- name: remove wifi-device channel
  uci:
    command: delete
    config: "wireless"
    section: "{{name}}"
    option: "channel"
  when: channel == {}
  notify:
    - uci commit wireless
    - reload network for openwrt-wireless

- name: set wifi-device txpower
  uci:
    command: set
    config: "wireless"
    section: "{{name}}"
    option: "txpower"
    value: "{{txpower}}"
  when: txpower != {}
  notify:
    - uci commit wireless
    - reload network for openwrt-wireless

- name: remove wifi-device txpower
  uci:
    command: delete
    config: "wireless"
    section: "{{name}}"
    option: "txpower"
  when: txpower == {}
  notify:
    - uci commit wireless
    - reload network for openwrt-wireless

- name: set wifi-device country
  uci:
    command: set
    config: "wireless"
    section: "{{name}}"
    option: "country"
    value: "{{country}}"
  when: country != {}
  notify:
    - uci commit wireless
    - reload network for openwrt-wireless

- name: delete wifi-device country
  uci:
    command: delete
    config: "wireless"
    section: "{{name}}"
    option: "country"
  when: country == {}
  notify:
    - uci commit wireless
    - reload network for openwrt-wireless
