---
- name: set wifi-iface device
  uci:
    command: set
    index: "{{index}}"
    config: "wireless"
    type: "wifi-iface"
    option: "device"
    value: "{{device}}"
  when: device != {}

- name: set wifi-iface network
  uci:
    command: set
    index: "{{index}}"
    config: "wireless"
    type: "wifi-iface"
    option: "network"
    value: "{{network}}"
  when: network != {}

- name: set wifi-iface mode
  uci:
    command: set
    index: "{{index}}"
    config: "wireless"
    type: "wifi-iface"
    option: "mode"
    value: "{{mode}}"
  when: mode != {}

- name: set wifi-iface ssid
  uci:
    command: set
    index: "{{index}}"
    config: "wireless"
    type: "wifi-iface"
    option: "ssid"
    value: "{{ssid}}"
  when: ssid != {}

- name: set wifi-iface encryption
  uci:
    command: set
    index: "{{index}}"
    config: "wireless"
    type: "wifi-iface"
    option: "encryption"
    value: "{{encryption}}"
  when: encryption != {}

- name: set wifi-iface key
  uci:
    command: set
    index: "{{index}}"
    config: "wireless"
    type: "wifi-iface"
    option: "key"
    value: "{{key}}"
  when: key != {}

- name: remove wifi-iface key
  uci:
    command: delete
    index: "{{index}}"
    config: "wireless"
    type: "wifi-iface"
    option: "key"
  when: key == {}

- name: set wifi-iface macfilter
  uci:
    command: set
    index: "{{index}}"
    config: "wireless"
    type: "wifi-iface"
    option: "macfilter"
    value: "{{macfilter}}"
  when: macfilter != {}

- name: remove wifi-iface macfilter
  uci:
    command: delete
    index: "{{index}}"
    config: "wireless"
    type: "wifi-iface"
    option: "macfilter"
  when: macfilter == {}

- name: set wifi-iface maclist
  uci:
    command: set_list
    index: "{{index}}"
    config: "wireless"
    type: "wifi-iface"
    option: "maclist"
    value: "{{maclist}}"
  when: maclist != {}

- name: remove wifi-iface maclist
  uci:
    command: delete
    index: "{{index}}"
    config: "wireless"
    type: "wifi-iface"
    option: "maclist"
  when: maclist == {}
